/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package languagelessons;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.printf("Java version of app = %s", Runtime.version());

    }
}
